version: "3"

networks:
  loki:

services:
  app:
    image: zhandos1609/moscow-time:${APP_TAG}
    deploy:
      resources:
        limits:
          memory: 256M
    container_name: app
    ports:
      - "5000:5000"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
        tag: "{{.ImageName}}|{{.Name}}"
    networks:
      - loki

  loki:
    image: grafana/loki:${LOKI_TAG}
    deploy:
      resources:
        limits:
          memory: 256M
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
        tag: "{{.ImageName}}|{{.Name}}"

  promtail:
    image: grafana/promtail:${PROMTAIL_TAG}
    deploy:
      resources:
        limits:
          memory: 256M
    container_name: promtail
    volumes:
      - /var/log:/var/log
      - /var/lib/docker/containers/:/var/lib/docker/containers/
      - ./promtail.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    networks:
      - loki
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
        tag: "{{.ImageName}}|{{.Name}}"

  grafana:
    image: grafana/grafana:${GRAFANA_TAG}
    deploy:
      resources:
        limits:
          memory: 256M
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - loki
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
        tag: "{{.ImageName}}|{{.Name}}"

  prometheus:
    image: prom/prometheus:${PROMETHEUS_TAG}
    deploy:
      resources:
        limits:
          memory: 256M
    container_name: prometheus
    ports:
    - 9090:9090
    command: --config.file=/etc/prometheus/prometheus.yml
    volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - loki
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
        tag: "{{.ImageName}}|{{.Name}}"
