global:
  scrape_interval:     10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: app
    static_configs:
      - targets: ['localhost:5000']
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
  - job_name: loki
    static_configs:
      - targets: ['loki:3100']
