apiVersion: apps/v1
kind: Deployment
metadata:
  name: moscow-time
  labels:
    app: moscow
spec:
  replicas: 3
  selector:
    matchLabels:
      app: moscow
  template:
    metadata:
      labels:
        app: moscow
    spec:
      containers:
      - name: moscow
        image: zhandos1609/moscow-time:latest
        ports:
        - containerPort: 5000