---
# tasks file for deploy_app
- name: Create directory
  file:
    path: "{{ install_path }}"
    state: directory
- name: Copy docker-compose file
  template:
    src: docker-compose.yml
    dest: "{{ install_path }}/{{ docker_compose_name }}"
    mode: 600
    owner: root
    group: root
- name: Run docker-compose
  docker_compose:
    project_src: "{{ install_path }}"
    files:
      - "{{ docker_compose_name }}"
    state: present
    pull: true
